string zoneId                       # ID of the zone

string zoneType                     # Type of the zone

string name                         # Name of the zone
 
string description                  # Description of the zone

string mapId                        # ID of the map that this zone belongs to.

ZoneParameter[] zoneParameters      # Parameters of the zone

ZonePolygonPoint[] polygon          # List of points that form the polygon of the zone
