float64 left_width                  #  Defines the width of the corridor in meters to the left related to the trajectory of the vehicle.
float64 right_width                 #  Defines the width of the corridor in meters to the right related to the trajectory of the vehicle.
string corridor_ref_point           #  Defines whether the boundaries are valid for the kinematic center or the contour of the vehicle.

#Enums for corridor_ref_point
string KINEMATICCENTER="KINEMATICCENTER"
string CONTOUR="CONTOUR"
