vda5050_msgs/VersionInfo[] versions     # Array of key-value pair objects containing
                                        # software and hardware information

vda5050_msgs/Network network            # Information about the vehicle's network
                                        # connection. The listed information shall not
                                        # be updated while the vehicle is operating

